name: GitHub Pages

on:
  push:
    branches: ['main']
    tags: ['*']

jobs:
  upload-docs:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    env:
      DOCS_DIR: 'docs/'
      OUTPUT_DIR: '_site/'
      MAIN_BRANCH: 'main'
    steps:
      - name: Configure pages
        uses: actions/configure-pages@v5
        id: configure-pages
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.MAIN_BRANCH }}
          fetch-depth: 0 # checkout a non-shallow copy so the generator can generate docs for all major versions
      - uses: gopxl/docs@main
        with:
          site-url: ${{ steps.configure-pages.outputs.base_url }}
          docs-directory: ${{ env.DOCS_DIR }}
          output-directory: ${{ env.OUTPUT_DIR }}
          main-branch: ${{ env.MAIN_BRANCH }}
      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.OUTPUT_DIR }}
      - name: Deploy pages
        uses: actions/deploy-pages@v4